language: java
install: true
jdk: openjdk8

script:
  - mvn clean package


cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.m2/repository'

after_success:
  - bash <(curl -s https://codecov.io/bash)